In [39]:
#These are libraries that you should import if needed for your notebook.
#import libraries
from datascience import *
import pandas as pd
import seaborn as sns
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

# Basics

Built-in Data Types
In programming, data type is an important concept.

Variables can store data of different types, and different types can do different things.

Python has the following data types built-in by default, in these categories:


*  Text or string Type:	  str
   *  Much of the world’s data is text, and a piece of text represented in a computer is called a string. A string can represent a word, a sentence, or even the contents of every book in a library.
*  Numeric Types:	int, float, complex
   *  Integers are called int values in the Python language. They can only represent whole numbers (negative, zero, or positive) that don’t have a fractional component
   * Real numbers are called float values (or floating point values) in the Python language. They can represent whole or fractional numbers but have some limitations.
*  Sequence Types:	list, tuple, range
   * Values can be grouped together into collections, which allows programmers to organize those values and refer to all of them with a single name. By grouping values together, we can write code that performs a computation on many pieces of data at once.
*  Mapping Type:	dict
*  Set Types:	  set, frozenset
*  Boolean Type:	  bool

## Operations

Python operators are special symbols (sometimes called keywords) that are used to perform certain most commonly required operations on one or more operands (value, variables, or expressions).

Python language supports the following types of operators:

* Arithmetic Operators

* Comparison (Relational) Operators

* Assignment Operators

* Logical Operators

* Bitwise Operators

* Membership Operators

* Identity Operators

In [ ]:
#Print Hello World
print("Hello world")

In [ ]:
#Print a number
print(5)


In [ ]:
#Add two numbers
5 + 5


In [ ]:
#Subtract one number from another
10 - 5

In [ ]:
#Multiply two numbers
8 * 8

In [ ]:
#Divide one number by another
16 / 8

In [5]:
#Calculate 2 to the power of 3
x = 2*2*2
xx = pow(2, 3)
print(xx)

8


## Variables

Variables are containers for storing data values. Unlike other languages, such as Java, Python has no command for declaring a variable, so you create one the moment you first assign a value to it.

* A variable name must start with a letter or the underscore character
* A variable name cannot start with a number
* A variable name can only contain alpha-numeric characters and underscores (A-z, 0-9, and _ )
* Variable names are case-sensitive (age, Age and AGE are three different variables)
* A variable name cannot be any of the Python keywords.

In [6]:
#Store the value of 5 in variable a.
a = 5

In [7]:
#What is the value of variable a
a

5

In [8]:
#Multiply variable a by another number
a * 5

25

In [9]:
#Add a number to  variable a
a + 20

25

In [10]:
#Change the value of variable a
a = 15

In [11]:
#Multiply variable a by a number
a * a

225

In [14]:
#Add variables a and b.
b = 25
a + b

40

In [ ]:
#Store the value of 15 in variable b
b = 15

In [15]:
#Create a new variable (total) and equate that to the value of a and b
total = a + b

In [16]:
#What is the value of total
total

40

In [68]:
#Create a variable (new) and equate that to a string 'Stellenbosch'
new = "Stellenbosch"

In [70]:
#Add 5 to variable new
new = "Stellenbosch" + 5

TypeError: can only concatenate str (not "int") to str

In [71]:
#Multiply the variable new by a number
new * 5


'StellenboschStellenboschStellenboschStellenboschStellenbosch'

**Class Exercise 1:**

In [19]:
# three new variables hourly_minimum_wage, hours_per_week, and weeks_per_year and equate them to
#15, 40 and 52 respectively
hourly_minimum_wage = 40 
hours_per_week = 15
weeks_per_year = 52

In [20]:
hourly_minimum_wage


40

In [22]:
#Determine the number of working hours in a year, store it in a variable, and output that
hours_per_year = weeks_per_year * 24
hours_per_year

1248

In [27]:
#Determine the minimum earning per year
x = hourly_minimum_wage * hours_per_year 
x


49920

In [29]:
#Determine the minimum earning per year using the original variables that were defined
print(hourly_minimum_wage * hours_per_year )

49920


## Arrays

Arrays represent multiple data elements of the same type using a single name. An array is a special variable, which can hold more than one value at a time.

In [54]:
#np.array is used to create an array
np.array([])

array([], dtype=float64)

In [63]:
#Equate the above array to A
A = np.array([])

In [56]:
#Multiply A by a number, what do you notice?
A * 5
A

array([], dtype=float64)

In [80]:
#Add a number to A, what do you notice?
number = np.append(A, 5)
# append
number

array([10., 10., 10., 10.,  5.])

In [82]:
#Use add the elements of A
A = np.add(A, 10)
A

array([30., 30., 30., 30.])

**Class Exercise 2:**

In [84]:
#Create a new array with elements 11, 13, 15 and 17 and store it in variable B
B = np.array([11, 13, 15, 17])

In [85]:
#Add A and B, what do you notice?
A + B

array([41., 43., 45., 47.])

In [86]:
#Create a new variable a and equate that to number
a = 15

In [87]:
#Add a and B
a + B

array([26, 28, 30, 32])

In [91]:
#Create two variables a and b and equate that to 9 and 5.
#Then create an array with the first element a+b and second element a*b

a = 9
b = 5

array1 = np.array([a+b])
array2 = np.array([a*b])
print (array1)
print (array2)


[14]
[45]


In [97]:
#Create a new array with elements 4, 5 and 7; and store it in variable C
C = np.array([4, 5, 7])

In [98]:
# Display A
A

array([30., 30., 30., 30.])

In [99]:
# print A
print(A)

[30. 30. 30. 30.]


In [100]:
#Add A and C  .Be mindful of the error
A + C

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

## Create a basic array

When it comes to creating a sequence of values, linspace and arange are two commonly used NumPy functions.

Here is the subtle difference between the two functions:

* linspace allows you to specify the number of steps
* arange allows you to specify the size of the steps
The following examples show how to use each function in practice.

### np.arange

The np.arange() function uses the following basic syntax:

np.arange(start, stop, step, …)

where:

* start: The starting value of the sequence
* stop: The end value of the sequence
* step: The spacing between values

In [104]:
#np.arange can take in 1, 2 or 3 inputs. When it takes one input, it creates an array from 0 as the first element
#with each subsequent element increasing by 1 until it reaches a number less than the input number.
#Write an np.arange command with one input. Let that input be 7.

d = np.arange(7)
d


array([0, 1, 2, 3, 4, 5, 6])

In [106]:
#What if I wanted the array to start at 1 and end in the value of the input
d = np.arange(1, 7)
d

array([1, 2, 3, 4, 5, 6])

In [110]:
#Let's try np.arange with two inputs seperated by a comma. The two inputs can be 1 and 8.
# d = np.arange(1, 8)
d = np.arange(1),(8)
d

(array([0]), 8)

In [113]:
# Create an array that starts with 200 and ends 211
e = np.arange(200, 212)
e

array([200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211])

In [117]:
#Let's try np.arange with two inputs seperated by a comma. The two inputs can be 1 and 8.  np.arange(start, stop, step, …)
f = np.arange(1,8,2)
print(f)

[1 3 5 7]


In [122]:
#Create two arrays using np.arange. The first array should use one input(5) and the second one using two inputs (10 and 13).
#Now, use np.append with two inputs. The two inputs are the arrays from above.
#What does np.append do

AA = np.arange(5)
# BB = np.arange(10 and 13)
BB = np.arange(10 and 13)

print(AA)
print(BB)

[0 1 2 3 4]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


### np.linspace

The np.linspace() function uses the following basic syntax:

 np.linspace(start, stop, num, …)

where:

* start: The starting value of the sequence
* stop: The end value of the sequence
* num: the number of values to generate

In [123]:
#create sequence of 11 evenly spaced values between 0 and 20
a = np.linspace(0, 20, 11)
a

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [124]:
a = np.linspace(0, 10, 3)
print(a)

[ 0.  5. 10.]


In [125]:
print(a.dtype)


float64


In [129]:
# Change the dtype to int
a_int = np.linspace(0, 10, 3, dtype=int)
a

array([ 0.,  5., 10.])

In [130]:
print(a_int.dtype)



int64



**Class Exercise 3**:

Create an array that ranges from 3 to 10 (inclusive). Another from 13 to 20 (inclusive). Add the two arrays.

In [131]:
array1 = np.arange(3, 10)
array2 = np.arange(13, 20)

print(array1 + array1)

[ 6  8 10 12 14 16 18]


Generate a reverse order array with np.arange() from 9 to 2 with a step size of 2

In [134]:
reverse_array = np.arange(9, 2, -2)
print(reverse_array)

[9 7 5 3]


# TAKE-HOME EXERCISE 1

**Complete the following take-home exercise for the next workshop session:**

You have a class of 10 students. Each student has completed two tests and one exam. The total scores for the tests were 70 and 80 respectively and the total score for the exam was 120. Test one and two each make up 25% of the final mark for the module, while the exam makes up the rest.

The scores for the students, out ouf their respective totals, are as follows...

For test 1 = 65, 63, 68, 40, 55, 43, 69, 52, 51, 48

For test 2 = 77, 79, 70, 35, 50, 46, 80, 56, 56, 52

For the exam = 110, 109, 100, 55, 60, 61, 115, 96, 99, 75


Make use of arrays to caclulate the following:
1.   The final mark (%) of each student.
2.   The class average (%) for each assesment as well as for the module.
3.   BONUS: Give the hightest and lowest final marks for the module (use Google).



# Tables

Tables are a fundamental object type for representing data sets. A table can be viewed in two ways:

* a sequence of named columns (i.e features or attributes) that each describe a single aspect of all entries in a data set, or

* a sequence of rows (data points or data instances) that each contain all information about a single entry in a data set.....

In [ ]:
#Upload olympics2024.csv file
from csv import files
uploaded = files.upload()


In [141]:
#Read the file into a table called olympics


In [ ]:
#Output the table, olympics to the screen


In [ ]:
#Show only the top three rows of the table


In [ ]:
#Show only the top ten rows of the table


In [ ]:
#Show all rows of the table excluding the last 10


In [ ]:
#Show only the last five rows of the table


In [ ]:
#Show only the last ten rows of the table
