# Importing numpy

ITAPA week 4

https://numpy.org/devdocs/

In [7]:
import numpy as np
import numpy.linalg as la 

This array class ndarry

import numpy as np
x = np.zeros(10)

output = [0,0,0,0...]

In [3]:
x = np.zeros((2, 10))
x
# 2D array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [4]:
x = np.zeros((2, 2, 2))
x
# 3D array

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [5]:
x = np.diag(np.ones(10))
x

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [11]:
np.arange(10, 100, 10)


array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [12]:
np.linspace(0.0, 1.0, 12)
# generates samples that are evenly seperated(middle point) and how many is the last number(endpoint)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [13]:
np.diag(np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

Creating arrays helps with standardization of data

# Creating random arrays

In [ ]:
# uniform distribution -> equal chance of occuring

# normal distribution -> bell curve 

In [17]:
import numpy as np
x = np.arange(9).reshape((3, 3))
print(x)

print(x[0:]) # First row

print(x[:,0]) # first column

print(x[1:3, :]) # Subarray

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 3 6]
[[3 4 5]
 [6 7 8]]


In [18]:
x = np.arange(9)
x
###
y = x.reshape((3, 3))
y
###
z = y.ravel()
z


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

# Arithmetic broadcasting

In [19]:
x = np.arange(5)*10
x


array([ 0, 10, 20, 30, 40])

In [20]:
y = -x
y

array([  0, -10, -20, -30, -40])

In [21]:
z = y+x
z
# has to have the same amount of elements

array([0, 0, 0, 0, 0])

# Pandas

dataframes will be used and series

-> Same data type must be used or catered for 
-> Statistical analysis 
-> missing data
-> data manipulation 

link: http://pandas.pydata.org/

In [22]:
import pandas as pd
# df = dataframes , we assigned a dataframe to it. you can use any word

how to read a CSV file __________^-^

In [24]:
df = pd.read_csv('/Salaries.csv')

# optional arguments can be used


In [ ]:
df.head(10)

In [ ]:
df.groupby(['wage'])

# groupby -> split the data groups on some criteria

To see more on this , refer to ITSCA or documentation on this!