# Confidence Intervals

### In statistics, a percentile is a term that describes how a score compares to other scores from the same set. While there is no universal definition of percentile, it is commonly expressed as the percentage of values in a set of data scores that fall below a given value.

###  Example S = [2,7, 3, 1, 9];
### S_sorted = [1, 2, 3, 7, 9];

### 80th percentile  = 7    i.e (80/100) * 5  ordered element







In [2]:
#These are libraries that you should import if needed for your notebook.
#import libraries
import pandas as pd
import seaborn as sns
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
#from google.colab import files

In [3]:
# Percentiles
# Creat an array
s = np.array([45, 45, 56, 33, 23, 67, 56, 88])
s


array([45, 45, 56, 33, 23, 67, 56, 88])

In [4]:
# Sort the code
np.sort(s)

array([23, 33, 45, 45, 56, 56, 67, 88])

In [7]:
# Let determine the 55th percentile of the array
np.arange(1, 7)/6
# Our 50% percentile lies between? 0.333 - 0.666 


array([0.16666667, 0.33333333, 0.5       , 0.66666667, 0.83333333,
       1.        ])

In [8]:
#np.sort(s)[3]
np.sort(s)[3]

np.int64(45)

In [9]:
# Alternatively: One line of code
np.percentile(s, 50)

np.float64(50.5)

## **Inference: Estimation**

### How do we calculate the value of an unknown parameter?
### If you have a census (i.e., data for the whole population): Just calculate the parameter, and you’re done


### But if you don’t have a census:


### Take a random sample from the population


### Use a statistic as an estimate of the parameter


### __One sample ➜ One estimate__

### But the random sample could have come out differently

### So the estimate could have been different

## Big question: How different would it be if we did it again?


In [ ]:
#upload the file san francisco .csv
uploaded=files.upload()

Saving san_francisco_2019.csv to san_francisco_2019.csv


In [14]:
#Read the file san_franscisco.csv
san_franscisco = pd.read_csv('C:/University/University Files/University-Code/Year 1/Semester 1/Python/Lessons/Data/csv/san_francisco_2019.csv')

In [15]:
# Lets view the dataframe
san_franscisco

Organization Group               Department  \
0                     Public Protection          Adult Probation   
1                     Public Protection          Adult Probation   
2                     Public Protection          Adult Probation   
3                     Public Protection          Adult Probation   
4                     Public Protection          Adult Probation   
...                                 ...                      ...   
44520  General Administration & Finance  Treasurer/Tax Collector   
44521  General Administration & Finance  Treasurer/Tax Collector   
44522  General Administration & Finance  Treasurer/Tax Collector   
44523  General Administration & Finance  Treasurer/Tax Collector   
44524  General Administration & Finance  Treasurer/Tax Collector   

                Job Family                             Job    Salary  \
0      Information Systems              IS Trainer-Journey   91332.0   
1      Information Systems           IS Engineer-Assistant  123241.0   
2      Information Systems      IS Business Analyst-Senior  115715.0   
3      Information Systems   IS Business Analyst-Principal  159394.0   
4      Information Systems           IS Programmer Analyst   70035.0   
...                    ...                             ...       ...   
44520              Revenue     Investigator, Tax Collector   44961.0   
44521              Revenue     Investigator, Tax Collector   85706.0   
44522              Revenue     Investigator, Tax Collector  101403.0   
44523              Revenue  Pr Investigator, Tax Collector  113738.0   
44524              Revenue  Pr Investigator, Tax Collector  113237.0   

       Overtime  Benefits  Total Compensation  
0           0.0   40059.0            131391.0  
1           0.0   49279.0            172520.0  
2           0.0   46752.0            162468.0  
3           0.0   57312.0            216706.0  
4           0.0   28671.0             98706.0  
...         ...       ...                 ...  
44520      42.0   19546.0             64549.0  
44521     107.0   38924.0            124737.0  
44522       0.0   43185.0            144587.0  
44523     397.0   47104.0            161240.0  
44524       0.0   49749.0            162986.0  

[44525 rows x 8 columns]

In [9]:
# Who made the most money show the first 5




In [10]:
# Who made the least money show the first 5


In [11]:
# # $15/hr, 20 hr/wk, 50 weeks
# Lets focus on people with salary above minimum


In [ ]:
# lets us now count the new number of Sf


(37103, 8)

In [12]:
# Plot the histogram distribution of the Total Compensation column  with bins ranging from 0 to 726000 with step size of 25000 with rotated x - axis xticks vertical


## Parameter: Median Total Compensation

In [13]:
# The median of the Total Compensation column


In [14]:
# The 50th percentile of the Total Compensation column


# Estimate the Parameter with the assumption it is unknown

In [15]:
# Sample sf without replacement 400 times


In [16]:
# Plot the histogram distribution of our_sample


In [17]:
# The 50th percentile of the Total Compensation column



 # But the random sample could have come out differently

# So the estimate could have been different

# Big question: How different would it be if we did it again?

In [ ]:
# But in the real world we won't be able to keep going back to the population. How to generate a new random sample without going back to the population?

## Quantifying Uncertainty

* The estimate is usually not exactly right:
* Estimate = Parameter + Error
* Error = Estimate - Parameter
* Parameter is fixed.
* Error variability is due to Estimate variability.
* How accurate is a typical Estimate?
* How big is a typical Error?
* When we have a census, we can do this by simulation


## Bootstrap

Sample randomly
 - from the original sample
 - with replacement
 - the same number of times as the original sample size

In [18]:
# Default behavior of tbl.sample:
# at random with replacement,
# the same number of times as rows of tbl



In [19]:
# Plot the histogram distribution of bootstrap_sample


## Bootstrap Sample Median
This is one estimate of the population median.

In [20]:
# The 50th percentile of the Total Compensation column


In [22]:
#def one_bootstrap_median(a):


In [23]:
#one_bootstrap_median(400)

In [24]:
# Generate the medians of 1000 bootstrap samples


In [25]:
# Create a new table called reampled_medians with column titled 'Bootsrap sample median' with values of a array bstrap_medians


In [26]:


##resampled_medians = pd.DataFrame({'Bootstrap Sample Median': bstrap_medians})
median_bins=np.arange(120000, 160000, 2000)
#plots.figure(figsize=(18, 10))

#resampled_medians.hist(bins = median_bins)

## Plotting parameters; you can ignore this code
#parameter_green = '#32CD32'
##plots.ylim(-0.000005, 0.00014)
#plots.xticks(rotation=90)
#plots.scatter(pop_median, 0, color=parameter_green, s=100, zorder=2)
#plots.title('Bootstrap Medians and the Parameter (Green Dot)');

## Percentile Method: Middle 95% of the Bootstrap Estimates