**Conditionals and Iterations**

A conditional statement is one where an action is performed if a prespecified condition is satisfied and another or no action is performed if the condition is not satisfied.

Conditional statements are an easy way to take different actions based on some condition being fulfilled or not.

In Python, we use the *if* statement for the conditional statement.

An iteration is a set of statement that is repeated multiple times.

Iteration will repeat a set of code and perform some action multiple times.

In Python, we use *for* statement for the iteration instruction.


**Advantages:**

* Simplifies coding.

* Readability.

* Efficiency in memory utilization.

In [3]:
#These are libraries that you should import if needed for your notebook.
#import libraries
import pandas as pd
import seaborn as sns
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
#from google.colab import files

## Conditional Statements

**if statement**

In [15]:
#Toss a coin.
coin = np.random.choice(['heads', 'tails'])

In [16]:
#what is the value of coin
coin

np.str_('tails')

In [17]:
#If the coin lands on heads, Marike wins.
if coin == 'heads':
    print("Marike wins")

**if-else statement**

In [ ]:
#If the coin lands on heads, Marike wins. If the coin lands on tail, Sunday wins.
# coin = "tails"

if coin == 'tails':
    print("Sunday wins")
else:
    print("Marike wins")

In [ ]:
#let's put the toss and the conditional statement together
coin = np.random.choice(['heads', 'tails'])
if coin == 'tails':
    print("Sunday wins")
if coin == "heads":
    print("Marike wins")
else:
    print("Invalid input")


Everytime we want to run the above code, we could just press run. This is tiring.

**if-elif-else statement**

In [18]:
#generate a random number between 1 and 6 (inclusive). It's like rolling a dice.
dice_throw = np.random.randint(1, 7)
dice_throw

2

In [ ]:
#let's create a conditional statement where if the random number is less than or equal to 3, Marike wins. If the number is equal to 4 or 5, Kanshu wins.
#If it is equal to 6, the Sunday wins.
if dice_throw <= 3:
    print("Marike wins")
elif dice_throw <= 5:
    print("Kanshu wins")
else:
    print("Sunday wins")

In [ ]:
#Let's put it all together
dice_throw = np.random.randint(1, 7)
if dice_throw <= 3:
    print("Marike wins")
elif dice_throw == 4 or dice_throw == 5:
    print("Kanshu wins")
elif dice_throw == 6:
    print("Sunday wins")

**We could replace the last elif with else as a catch all condition, that must be run if no former conditions are fulfilled.**

In [ ]:
#Let's put it all together
dice_throw = np.random.randint(1, 7)
if dice_throw <= 3:
    print("Marike wins")
elif dice_throw == 4 or dice_throw == 5:
    print("Kanshu wins")
elif dice_throw == 6:
    print("Sunday wins")
else:
    print("Fufilled")

**Everytime I want to run the code above, I click on the run button again and again. This is tiring.**

**Nested if statements**

In [ ]:
#Roll a dice. If the number is less than 3, Marike wins.
#If greater than 3, then a coin is tossed and if the coin is heads, then Kanshu wins, else Sunday wins.
dice_throw = np.random.randint(1, 7)
if dice_throw <= 3:
    print("Marike wins")
else:
    coin = np.random.choice(['heads', 'choice'])
    if coin == 'heads':
        print("Kanshu wins")
    else:
        print("Sunday wins")
 


## Iterations

Iterations allows us to repeat code multiple times.



In [19]:
#Remember np.arange(1,7)
np. arange(1, 7)

array([1, 2, 3, 4, 5, 6])

In [20]:
#Let's write a for statement
for i in np.arange(1, 7):
    print(i)

1
2
3
4
5
6


In [22]:
#what if we use np.arange(5,9)
np.arange(5,9)

array([5, 6, 7, 8])

In [23]:
#What if we put strings in the array
for i in ['A', 'N']:
    print (i)


A
N


In [24]:
#Let's generate multiple throws of dice
np.random.randint(1, 7, 10)

array([1, 6, 5, 3, 5, 3, 2, 6, 3, 4], dtype=int32)

In [26]:
#Now we want to use these numbers to determine whether Marike, Kanshu or Sunday won based on the conditions given earlier
dice_throw = np.random.randint(1, 7, 10)
for i in dice_throw:
    if i <= 3:
        print("Marike wins")
    elif i == 4 or i == 5:
        print("Kanshu wins")
    elif i == 6:
        print("Sunday wins")

Marike wins
Sunday wins
Kanshu wins
Marike wins
Marike wins
Sunday wins
Kanshu wins
Kanshu wins
Marike wins
Marike wins


In [29]:
#Let's create an array with the results
results =[]

dice_throw = np.random.randint(1, 7, 4)

for i in dice_throw:
    if i <= 3:
        answer = 'Marike'
    elif i == 4 or i == 5:
        answer = 'Kanshu'
    else:
       answer = 'Sunday'

    results.append(answer)
    
print(results)

['Kanshu', 'Marike', 'Marike', 'Marike']


In [ ]:
#Let's make this neater


In [ ]:
#how many times did Kanshu win
#depends on your output you get but...
results.count('Kanshu')

In [ ]:
#how many times did Marike win
#how many times did Kanshu win
[results.count('Marike'), results.count('Kanshu')]

**While loop basics**

In [31]:
#i = 1. Run a loop such that while i is less than 5, print i
i = 1
while i != 5:
    print(i)
    i += 1
    

1
2
3
4


**break statement**


In [34]:
#Let's see how we can exit a for loop
for i in np.arange(1, 10):
    if i == 5:
        break
    print(i)



1
2
3
4


## Exercise

Suppose you toss a coin and throw a dice. If the coin lands on heads and the dice is less than or equal to 3, Kanshu wins. If the coin lands on heads and dice is greater than 3, Sunday win. If the coin lands on tails and the dice is equal to 1, Sunday wins. If the coin lands on tails and the dice is greater than or equal to 2, Marike win.

Run the above simulation 100 times and count the number of times that each person wins.

In [11]:

results = []

dice_throws = np.random.randint(1, 7, 100)

for dice_throw in dice_throws:
    coin_throw = np.random.choice(['Heads', 'Tails'])

    if (coin_throw == 'Heads' and dice_throw <= 3):
        answer = "Kanshu"
    elif (coin_throw == 'Heads' and dice_throw > 3) or (coin_throw == 'Tails' and dice_throw == 1):
        answer = "Sunday"
    elif (coin_throw == 'Tails' and dice_throw >= 2):
        answer = "Marike"
    else:
        answer = "None"
    
    results.append(answer)

[results.count('Marike'), results.count('Kanshu'), results.count('Sunday')]



[428, 255, 317]